# mpn aml columns for tab separated text file 
CHR = "chr"	
START = "start"	
END = "end"	
REF = "ref"	
ALT = "alt"	
REGION = "region"	
GENE = "gene"	
SAMPLEA = "sample"	
ID = "ID"	
SAMPLEB = "Sample"	
TIMEPOINT = "Timepoint"	
VAR_READS = "var_reads.pairtree"	
TOTAL_READS = "total_reads.pairtree"	
COPY_NUMBER = "celluloid.cn.av"